dataset: "ego2hands"
model_name: "CSM_TF"
dataset_train_dir: "data/Ego2Hands/train"
dataset_eval_dir: "data/Ego2Hands/eval/"
bg_all_dir: "data/Ego2Hands/backgrounds"
# Set the following parameters for custom scene training and testing
custom_bg_dir: "data/Ego2Hands/custom/custom_train"
custom_eval_dir: "data/Ego2Hands/custom/custom_eval"
custom_scene_brightness: "normal" #[dark, normal, bright]

workers: 4
batch_size: 64
num_seqs: 4
max_iter_seg: 200
max_iter_seg_adapt: 10
display_interval: 10
save_interval: 10
num_classes : 3
weight_decay: 0.001

base_lr_seg: 0.0001
base_lr_seg_adapt: 0.00001
#-------------lr_policy--------------------#
# step
lr_policy: 'step'
policy_parameter_seg:
  gamma: 0.5
  step_size: 20000
  
policy_parameter_seg_adapt:
  gamma: 0.5
  step_size: 5000

energy: false
save_outputs: true
adapt: false
input_edge: true
model_path: "saved_models"
dual_hands: false
speed_test: false
input_shape: [128, 128, 3]
dataset_train_preprocessed: "data/preprocessed/train"
dataset_eval_preprocessed: "data/preprocessed/eval"